spring:
  profiles:
    group:
      "dev": "testdb,common"
      "prod": "proddb, common"
    default: "testdb, common"

---
spring:
  config:
    activate:
      on-profile: "common"

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  web:
    resources:
      chain:
        enabled: true
        strategy:
          content:
            enabled: true
            paths: /**

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type : trace
    org.springframework.web : debug
    org.springframework.security: debug

---
spring:
  config:
    activate:
      on-profile: "testdb"

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
#      data-locations: "classpath*:db/h2/data-h2.sql"
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

---

spring:
  config:
    activate:
      on-profile: "proddb"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa_ex?useSSL=false
    username: jpa_user
    password: jpa_user_password

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
    database: mysql

    properties:
      hibernate:
        dialect:
          nodeValue: org.hibernate.dialect.MySQL57Dialect
          storage_engine: innodb
  sql:
    init:
      data-locations: "classpath*:/db/mysql/data-mysql.sql"
      mode: always
      platform: mysql


